# Generated by Django 3.1.5 on 2021-01-19 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_auto_20210118_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signuppro',
            name='pro_documents',
            field=models.FileField(default='', upload_to='documents/'),
        ),
    ]
