# Generated by Django 3.1.5 on 2021-01-20 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='nill', max_length=30)),
                ('service', models.CharField(default='nill', max_length=30)),
                ('servicedesc', models.TextField(default='nill', max_length=50)),
                ('time', models.CharField(default='nill', max_length=30)),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'servicemodel',
            },
        ),
    ]
